# Generated by Django 4.1.3 on 2024-02-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_cartitem_user_cartitem_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000000, null=True),
        ),
    ]
